name: CI DevSecOps Basico

on:
  push:
    branches: [main, develop, feature/luna_testeo-pipeline]
  pull_request:

jobs:
  build-test-sec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v3

    - name: Configurar WSL / entorno Linux
      run: sudo apt-get update && sudo apt-get install -y curl dig bats make

    - name: Instalaci칩n de netcat
      run: make netcat

    - name: Verificar instalaci칩n de bats
      run: make install-bats

    - name: Ejecutar pruebas b치sicas
      run: make test

    - name: Ejecutando todos los procesos
      run: |
        make run &
        sleep 2
        make run-procesos

    - name: Terminando todos los procesos
      run: make clean