name: CI DevSecOps Basico

on:
  push:
    branches: [main, develop, feature/luna_testeo-pipeline]
  pull_request:

jobs:
  build-test-sec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Instalación de dependencias
      run: |
        sudo apt-get update && sudo apt-get install -y curl dnsutils bats make
        make netcat
        make install-bats
        make lint

    - name: Ejecutar pruebas básicas
      run: make test

    - name: Ejecutando todos los procesos
      run: |
        make run &
        sleep 2
        make run-procesos

    - name: Terminando todos los procesos
      run: make clean

    - name: Uso de linters para scripts bash
      run: make check-lint